# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-07-18 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cscapp', '0002_auto_20170718_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
