# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-19 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cscapp', '0004_auto_20170718_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='code',
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
