# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-19 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cscapp', '0005_auto_20170719_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='Title', max_length=300, unique=True),
        ),
    ]
