# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-24 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cscapp', '0008_remove_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='introductory',
            field=models.TextField(blank=True, null=True),
        ),
    ]
