# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-24 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cscapp', '0009_course_introductory'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='unit',
            field=models.IntegerField(default=0),
        ),
    ]
